---

- name: Install Cribl
  hosts: cribl
  serial: 6
  become: true
  tasks:
    - name: Create /opt/cribl
      file:
        path: /opt/cribl
        state: directory
    - name: Download Sources
      unarchive:
        src: "{{ src }}"
        dest: "/opt/"
        mode: 0755
        remote_src: yes
        creates: /opt/cribl/etc/