---

- name: Checkout of Cribl Demo from github
  git:
    repo: "https://github.com/criblio/cribl-demo.git"
    dest: /srv/cribldemo
- name: This command will start a Cribl Demo Container using Docker-Compose
  command: docker-compose up -d
  args:
    chdir: /srv/cribldemo
